_wandb:
    value:
        cli_version: 0.23.1
        e:
            fsf9f7fl01x53fwpxh2sanoh5cunlvar:
                codePath: autonomous_vehicles/autonomous_vehicles/train_agent.py
                codePathLocal: autonomous_vehicles/autonomous_vehicles/train_agent.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "170040844288"
                        used: "150134460416"
                email: tmorawa@student.agh.edu.pl
                executable: /usr/bin/python3
                git:
                    commit: 66f7930dde99fcc39f6e227889bdef75dc06a211
                    remote: git@github.com:PaprykVegee/Controlling-a-mecanum-vehicle-using-MoE-and-RL.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-6725406d-30b7-7385-f5da-af1cecc5ab95
                host: tomek-Victus-by-HP-Gaming-Laptop-15-fa0xxx
                memory:
                    total: "33302364160"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.35
                program: /home/developer/ros2_ws/src/autonomous_vehicles/autonomous_vehicles/train_agent.py
                python: CPython 3.10.12
                root: /home/developer/ros2_ws/src
                startedAt: "2025-12-14T11:49:55.919906Z"
                writerId: fsf9f7fl01x53fwpxh2sanoh5cunlvar
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 63
                - 74
            "3":
                - 13
                - 16
                - 22
            "4": 3.10.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
algo:
    value: PPO
batch_size:
    value: 32
env_parallel:
    value: 1
gamma:
    value: 0.995
lr:
    value: 0.0001
max_steps_per_episode:
    value: 1800
n_epochs:
    value: 6
n_steps:
    value: 512
total_timesteps:
    value: 1000000
