bridges:
  - topic: /cmd_vel
    type: geometry_msgs/msg/Twist
    gz_type: gz.msgs.Twist

  - topic: /clock
    type: rosgraph_msgs/msg/Clock
    gz_type: gz.msgs.Clock

  - topic: /world/mecanum_drive/pose/info
    type: tf2_msgs/msg/TFMessage
    gz_type: gz.msgs.Pose_V




  - topic: /world/mecanum_drive/model/vehicle_blue/link/left_camera_link/sensor/left_camera_sensor/image
    type: sensor_msgs/msg/Image
    gz_type: gz.msgs.Image




  - topic: /world/mecanum_drive/model/vehicle_blue/link/right_camera_link/sensor/right_camera_sensor/image
    type: sensor_msgs/msg/Image
    gz_type: gz.msgs.Image



  - topic: /world/mecanum_drive/model/vehicle_blue/link/lidar_link/sensor/lidar/scan
    type: sensor_msgs/msg/LaserScan
    gz_type: gz.msgs.LaserScan